# Generated by Django 3.0.6 on 2020-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vid_id',
            field=models.CharField(default='5v1B1R3lEO8', max_length=255),
        ),
    ]
